#+TITLE: 
#+AUTHOR: 
#+EMAIL: 
#+DATE: 2026-04-01T21:13:40Z UTC 
#+LANGUAGE:  en 
#+EXPORT_FILE_NAME: TJOAChapter1.html
# --- Configurations ---
#+SETUPFILE: /home/galaxybeing/Dropbox/org/tufte-html-setup.org
#+SETUPFILE: /home/galaxybeing/Dropbox/org/math-latex-setup.org
# --- Bibliography ---
#+bibliography: /home/galaxybeing/Dropbox/org/biblio/ref.bib
#+cite_export: csl
# --- Document Content Starts Here ---
#+INCLUDE: /home/galaxybeing/Dropbox/org/codeismathiscode2/header.org :minlevel 1


* Categories: the idea
:PROPERTIES:
:CUSTOM_ID: categories-the-idea
:END:
/An overview of what the point of category theory is, without
formality./

I like to think of category theory as the mathematics of mathematics.

I admit this phrase sounds a bit self-important, and it comes with
another problem, which is the widespread misunderstandings about what
mathematics actually is. This problem is multiplied (or possibly raised
to the power of infinity) here by the reference of math to itself.

Another problem is that it might make it seem like you need to
understand the whole of mathematics before you could possibly understand
category theory. Indeed, that is not far from what the prevailing wisdom
has been about studying category theory in the past: that you have to,
if not understand /all/ of math, at least understand a large amount of
it, say up to a graduate level, before you can tackle category theory.
This is why category theory has traditionally only been taught at a
graduate level, and more recently sometimes to upper level
undergraduates who already have a solid background in upper level pure
mathematics. The received wisdom is that all the motivating examples
come from other branches of pure mathematics, so you need to understand
those first before you can attempt to understand category theory.

Questioning “received wisdom” is one of my favorite pastimes. I don't
advocate just blindly going against it, but the trouble with received
wisdom, like “common sense”, is that it too often goes unquestioned.

My experience of learning and teaching category theory has been
different from that received wisdom. I did first learn category theory
in the traditional way, that is, only after many undergraduate courses
in pure math. However, those other subjects didn't help me to understand
category theory, but the other way round: category theory was much more
compelling to me and I loved and understood it in its own right,
whereupon it helped me to understand all those other parts of pure math
that I had never really understood before.

I eventually decided to start teaching category theory directly as well,
to students with essentially no background in pure mathematics. I am
convinced that the ideas are interesting in their own right and that
examples illustrating those ideas can be found in life, not just in pure
math. That's why I'm starting this book with a chapter about those
ideas.

I think we can sometimes unintentionally fall into an educational scheme
of believing that we need to learn and teach math in the order in which
it was developed historically, because surely that is the logical order
in which ideas develop. This idea is summed up in the phrase “ontogeny
recapitulates phylogeny”, although that is really talking about
biological development rather than learning.† I think this has merit at
some levels. The way in which children grasp concepts of numbers
probably does follow the history of how numbers developed, starting with
the counting numbers 1, 2, 3, and so on, then zero, then negative
numbers and fractions (maybe the other way round) and eventually
irrational numbers. However, some parts of math developed because of a
lack of technology, and are now somewhat redundant. It is no longer
important to know how to use a slide rule. I know very few ruler and
compass constructions, but this has not hindered my ability to do
category theory, just like my poor skills in horse riding have not
hindered my ability to drive a car. Of course, horse riding can be
enjoyable, and even crucial in some walks of life, and by the same token
there are some specific situations in which mental arithmetic and long
division might be useful. Indeed some people simply enjoy multiplying
large numbers together. However, none of those things is truly a
prerequisite for meeting and benefiting from category theory.

Crucially, I think we can benefit from the ideas and techniques of
category theory even outside research math and aside from direct
technical applications. Mathematics is among other things a field of
research, a language, and a set of specific tools for solving specific
problems. But it is also a way of thinking. Category theory is a way of
thinking about mathematics, thus it is a way of thinking about thinking.
Thinking about how we think might sound a bit like convoluted
navel-gazing, but I believe it's a good way of working out how to think
better. And in a world of fake news, catchy but contentless memes, and
short attention spans, I think it's rather important for those who do
want to think better to find better and better ways of doing it, and
share them as widely as possible rather than keeping people under a
mistaken belief that you have to learn a huge quantity of pure math
first.

I have gradually realized that I use the ideas and principles of
category theory in all my thinking about the world, far beyond my
research, and in areas that probably wouldn't be officially considered
to be applications. It is these ideas and principles that I want to
describe in this first chapter, before starting to delve into how
category theory implements those ideas and how it trains us

† Also the phrase was coined by Ernst Haeckel who had some repugnant
views on race and eugenics, so I'm reluctant to quote him, but
technically obliged to credit him for this phrase.

in the discipline of using them all the time. This chapter is in a way
an informal overview of the entire book; it might seem a little vague
but I hope the ideas will become clearer as the book progresses.

We are going to build up to the definitions very gradually, so if you're
feeling impatient you might want to glance at Chapter 8 in advance, but
I urge you to read the chapters of build-up to get into the spirit of
this way of thinking. In the Epilogue I will come back to the ideas and
spirit of category theory, but from a more technical point of view after
we have met and explored the formalism.

**** 1.1 Abstraction and analogies
:PROPERTIES:
:CUSTOM_ID: abstraction-and-analogies
:END:
Mathematics relies heavily on abstraction to get it going. Its arguments
are all based on rigorous logic, and rigorous logic only works properly
in abstract settings. We can try and use rigorous logic in less abstract
settings, but we will probably always† run into problems of ambiguity:
ambiguity of definitions, ambiguity of interpretations, ambiguity of
behavior, and so on.

In normal life situations there is always the possibility that something
will get in the way of logic working perfectly. We might think that,
logically, one plus one is always two, but in real life some aspect of
the objects in question might get in the way. If someone gives you one
cookie and then another cookie you might have two cookies but it depends
if you ate them. If you had one flower and you buy another then you
might have two, but perhaps you bought another because the first one
died.

Abstraction is the process of deciding on some details to ignore in
order to ensure that our logic does work perfectly. In the situations
above this might consist of specifying that we don't eat the cookies, or
that the flowers don't die (or reproduce). This is an important part of
the process of doing mathematics because one of the aims is to eliminate
ambiguity from our arguments. This doesn't mean that ambiguity is bad;
indeed ambiguity is one of the things that can make human life rich and
beautiful. However, it can also make arguments frustrating and
unproductive. Math is a world in which one of the aims is to make
arguments unambiguous in order to reach agreement on something. We will
go into detail about how abstraction works and what its advantages and
disadvantages are in the next chapter. The idea is that abstraction
itself has the potential to be ambiguous, and category theory provides a
secure framework for performing abstractions.

† I am tempted to say “always” but my precise mathematical brain
prevents me from making absolute statements without some sort of
qualification such as “probably” or “I believe” or “it is almost
certainly true that”.

** 1.2 Connections and unification
:PROPERTIES:
:CUSTOM_ID: connections-and-unification
:END:
One of the aims and advantages of abstraction is to make connections
between different situations that might previously have seemed very
different. It might seem that abstraction takes us further away from
“real” situations. This is superficially true, but at the same time
abstraction enables us to make connections between situations that are
further apart from one another. This is one of the ways in which math
helps us understand more things in a more powerful way, by making
connections between different situations so that we can study them all
at once instead of having to do the work over and over again. Once we've
understood that one plus one is two (abstractly) we don't have to keep
asking ourselves that question for different objects. Spotting
similarities in our thought processes enables us to make more efficient
use of our brain power.

One way in which this arises is in pattern spotting. A pattern can arise
as a connection within a single situation, such as when we use a
repeating pattern to tile a floor or wall. Or it can arise as a
connection between different situations, such as when we see a pattern
of certain types of people dominating conversations or belittling
others, whether it's at work or in our personal lives, in “real life” or
online.

Making connections between different situations is a step in the
direction of unification. In math this doesn't mean making everything
the same, but it is more about making an abstract theory that can
encompass and illuminate many different things. Category theory is a
unifying theory that can simultaneously encompass a broad range of
topics and also a broad range of scales by zooming in and out, as we'll
see. Chapter 3 will be about patterns, and how this gives us a start at
recognizing abstract structures.

*** 1.3 Context
:PROPERTIES:
:CUSTOM_ID: context
:END:
One of the starting points of category theory is the idea that we should
always study things in context rather than in isolation. It's a bit like
always setting a frame of reference first. This is one crucial way to
eliminate ambiguity right from the start, because things can take on
very different meanings and different characteristics in different
contexts. Our example of one plus one giving different results was
really a case of context getting in the way of our logical outcomes. One
plus one does always equal two provided we are in a context of things
behaving like ordinary numbers and not like some other kind of number.
But there are plenty of contexts in which things behave differently, as
we'll see in Chapter 4. One of the disciplines and driving principles of
category theory is to make sure we are always aware of and specific
about what context we're considering. This is relevant in all aspects of
life as well. For example, the context of someone's life situation, how
they grew up, what is going on for them in their personal life, and so
on, has a big effect on how they behave, and what their achievements
represent. The same achievement is much more impressive to me when
someone has struggled against many obstructions in life, because of
race, gender, gender expression, sexual orientation, poverty, family
circumstance, or any number of other struggles. Sometimes this is
controversially referred to as “positive discrimination” but I prefer to
think of it as contextual evaluation.

*** 1.4 Relationships
:PROPERTIES:
:CUSTOM_ID: relationships
:END:
One of the crucial ways in which category theory specifies and defines
context is via relationships. It takes the view that what is important
in a given context is the ways in which things are related to one
another, not their intrinsic characteristics. The types of relationship
we consider are often key to determining what context we're in or should
be in. For example, in some contexts it matters how old people are
relative to one another, but in other contexts it matters what their
family relationships are, or how much they earn. But if we're thinking
about, say, how good different people will be at running a country, then
it might not seem relevant how much money they have relative to one
another. Except that in some political systems (notably the US) being
very rich seems quite important in getting elected to political office.

There can also be different types of relationship between the same
things in mathematics, and we might only want to focus on certain types
of relationship at any given moment. It doesn't mean that the others are
useless, it just means that we don't think they are relevant to the
situation at hand. Or perhaps we want to study something else for now,
in something a bit like a controlled experiment. Numbers themselves have
various types of relationship with each other. The most obvious
relationship between numbers is about size, and so we put numbers on a
number line in order of size. But we could put numbers in a different
diagram by indicating which numbers are divisible by others. In category
theory those are two different ways of putting a category structure on
the same set of numbers, by using a different type of relationship. We
will go into more detail about this in Chapter 5.

The relationships used in category theory can essentially be anything,
as long as they satisfy some basic principles ensuring that they can be
organized in a mildly tractable way. This will guide us to the formal
definition of a category. To build up to that we will look at the idea
of formalism in Chapter 6, to ease into this aspect of mathematics that
can sometimes be so offputting. In Chapter 7 we'll look at a particular
type of relationship called equivalence relations, which satisfy many
good properties making them exceedingly tractable. In fact, they satisfy
too many good properties, so they are too restrictive to be broadly
expressive in the way that category theory seeks.

We will see that category theory is a framework that achieves a
remarkable trade-off between good behavior and expressive possibilities.
If a framework demands too much good behavior then expressivity is
limited, as in a totalitarian state with very strict laws. On the other
hand if there are too /few/ demands, then there is great potential for
expressivity, but also for chaos and anarchy. Category theory achieves a
productive balance between those, in the way it specifies what type of
relationship it is going to study.

Part One of the book will build up to the formal definition of a
category. We will then take an Interlude which will be a tour of
mathematics, presenting various mathematical structures as examples of
categories. The usual way of doing this is to assume that a student of
category theory is already familiar with these examples and that this
will help them feel comfortable with the definition of category theory.
I will not do that, but will introduce those examples from scratch,
taking the ideas of category theory as a starting point for introducing
these mathematical topics instead. In Part Two of the book we will then
look more deeply into the sorts of things we do with category theory.

**** 1.5 Sameness
:PROPERTIES:
:CUSTOM_ID: sameness
:END:
One of the main principles and aims of category theory is to have more
nuanced ways of describing sameness. Sameness is a key concept in math
and at a basic level this arises as equality, along with the concept of
equations. Indeed, many people get the impression that math is /all/
about numbers and equations. This is very far from true, especially for
a category theorist. First of all, while numbers are an example of
something that can be organized into a category, the whole point is to
be able to study a much, much broader range of things than numbers.
Secondly, category theory specifically does not deal in equations
because equality is much too strong a notion of sameness in category
theory.

The point is, many things that we write with an equals sign in basic
math aren't really equal deep down. For example when we say 5 + 1 = 1 +
5 we really mean that the outcomes are the same, not that the two sides
of the equation are actually completely the same. Indeed, if the two
sides were completely the same there would be no point writing down the
equation. The whole point is that there is a sense in which the two
sides are different and a sense in which the two sides are the same, and
we use the sense in which they're the same to pivot between the senses
in which they're different in order to make progress and build up more
complex thoughts. We will go into this in Chapter 14.

Numbers and equations go together because numbers are quite
straightforward concepts,† so equality is an appropriate notion of
“sameness” for them. However, when we study ideas that are more complex
than numbers, much more subtle notions of sameness are possible. To take
a very far opposite extreme, if we are thinking about people then the
notion of “equality” becomes rather complicated. When we talk about
equality of people we don't mean that any two people are actually the
same person (which would make no sense) but we mean something more
subtle about how they should be treated, or what opportunities they
deserve, or how much say they should have in our democracy. Arguments
often become heated around what different people mean by “equality” for
people, as there are so many possible interpretations.

Math is about trying to iron out ambiguity and have more sensible
arguments. Category theory seeks to study notions of sameness that are
more subtle and complex than direct equality, but still unambiguous
enough to be discussed in rigorous logical arguments. Sometimes a much
better question isn't to ask whether two things are equal or not, but
/in what ways/ they are and aren't equal, and furthermore, if we look at
some way in which they're not equal, how much and in what ways do they
fail to be equal? This is a level of subtlety provided by category
theory which we sorely need in life too.

** 1.6 Characterizing things by the role they play
:PROPERTIES:
:CUSTOM_ID: characterizing-things-by-the-role-they-play
:END:
Category theory seeks to characterize things by the role they play in
context rather than by some intrinsic characteristics. This is related
to the idea of context and relationships being so important. Once we
understand that objects take on very different characteristics in
different contexts it becomes clearer that the whole idea of intrinsic
characteristics is rather shaky.

I think this applies to people as well. I don't think I have an
intrinsic personality because I behave very differently depending on
what sort of situation I'm in. In some situations I'm confident and
talkative, and in other situations I'm nervous and shy. Even
mathematical objects do something similar, although in that case the
characteristics we're thinking about aren't personality traits, but
mathematical behaviors.

† Actually they're very profound, but once they're defined there's not
much nuance to them.

For example, we might think the number 5 is prime “because it's only
divisible by 1 and itself”, but we really ought to point out that the
context we're thinking of here is the whole numbers, because if we allow
fractions then 5 is divisible by everything really (except 0).†

In normal life we often mix up when we're characterizing things by role
and by property in the way that we use language. For example “pumpkin
spice” is named after the role that this spice combination plays in
classic American pumpkin pie, but it has now come to be used as a
flavoring in its own right in any number of things that are not actually
pumpkin pie, but it's still called pumpkin spice, which is quite
confusing for non-Americans. Conversely “pound cake” is named after the
fact that it's a recipe consisting of a pound each of basic cake
ingredients. So it's named after an intrinsic property, and it's still
called pound cake even if you change the quantity that you use. I,
personally, have never made such an enormous cake.

One of the advantages of characterizing things by the role they play in
context is that you can then make comparisons across different contexts,
by finding things that play analogous roles in other contexts. We will
talk about this when we discuss universal properties in Chapter 16. This
might sound like the opposite of what I just described, as it sounds a
bit like properties that are universal regardless of context, but what
it actually refers to is the property of being somehow extreme or
canonical within a context. This can tell us something about the objects
with that property, but it can also tell us something about the context
itself. If we go round looking at the highest and lowest paid employees
in different companies, that tells us something about those companies,
not just about the employees. It is only one piece of information (as
opposed to a whole distribution of salaries across the company) but it
still tells us something.

** 1.7 Zooming in and out
:PROPERTIES:
:CUSTOM_ID: zooming-in-and-out
:END:
One of the powerful aspects of category theory's level of abstraction is
that it enables us to zoom in and out and look at large and small scale
mathematical structures in a similar light. It's like a theory that
unifies the sub-atomic level with the level of galaxies. This is one of
my favorite aspects of category theory.

If we study birds then we might need to make a theory of birds in order
to make our study rigorous. However, that theory of birds is not itself
a bird --- it's one level more abstract. On the other hand if we study
mathematical objects then we similarly might need a theory of them. I
find it enormously

† Also this is more of a characterization than a definition.

satisfying that that theory is itself also a mathematical object, which
we can then study using the same theory. Category theory is a theory of
mathematics, but is itself a piece of mathematics, and so it can be used
to study itself. This sounds self-referential, but what ends up
happening is that although we are still in category theory we find
ourselves in a slightly higher dimension of category theory. Dimensions
in this case refer to levels of relationship. In basic category theory
our insight begins by saying we should study relationships between
objects, not just the objects themselves. But what about the
relationships? If we consider those to be new mathematical objects,
shouldn't we also study relationships between those? This gives us one
more dimension.

Then, of course, why stop there? What about relationships between
relationships between relationships? This gives us a third dimension.
And really there is no logically determined place to stop, so we might
keep going and end up with infinite dimensions. This is essentially
where my research is, in the field of higher-dimensional category
theory, and we will see a glimpse of this to finish the book. To me this
is the ultimate “fixed point” of theories. If category theory is a
theory of mathematics, then higher-dimensional category theory is a
theory of categories. But a theory of higher-dimensional category theory
is still higher-dimensional category theory.

This is not just about abstraction for the sake of it, although I do
find abstraction fun in its own right. It is about subtlety. Category
theory is about having more subtle ways of expressing things while still
maintaining rigor, and every extra dimension gives us another layer of
possible subtlety.

Subtlety and nuance are aspects of thinking that I find myself missing
and longing for in daily life. So much of our discourse has become
black-and-white in futile attempts to be decisive, or to grab attention,
or to make devastating arguments, or to shout down the opposition.
Higher-dimensional category theory trains us in balancing nuance with
rigor so that we don't need to resort to black-and-white, and so that we
don't /want/ to either.

I think mathematics is a spectacular controlled environment in which to
practice this kind of thinking. The aim is that even if the theory is
not directly applicable in the rest of our lives, the thinking becomes
second nature. This is how I have found category theory to help me in
everyday life, surprising though it may sound.

** 1.8 Framework and techniques
:PROPERTIES:
:CUSTOM_ID: framework-and-techniques
:END:
As I have described it so far, category theory might sound like a
philosophy more than anything else. But the point is that it is only
/guided/ by these various philosophies. It is still entirely rigorous
technical mathematics. It sets up a framework for implementing these
philosophies and pursuing these goals rigorously. The framework consists
of a formal definition of a category as an algebraic structure, and then
techniques for studying these structures and for constructing and
investigating particular features that might arise in them.

To this end, a certain amount of formal mathematics is needed if we are
ever going to get very far into the theory itself, rather than
poetically exploring the ideas behind it. This is one of the things that
can be offputting about mathematics, and I do advocate the idea of
seeing and appreciating the ideas of math even if you can't or don't
want to follow the formality. However that is not the aim of this book.
(It was, in a way, the aim of my book /How to Bake/ π.) I do think that
way of appreciating mathematics is under-rated. It is a bit like going
to visit a country without learning to speak the language. I think it
would be culturally limiting for us to decide we should never visit a
country without learning the language first. However, I also think that
if we can learn at least some of the language then even if we're not
fluent we will get much more out of a visit. This is what this book is
for.

Mathematics is sometimes taught as if the only valid interaction with it
is to be able to do it. As I said in the Prologue, languages are taught
with a “productive” and a “receptive” component (as well as a cultural
component, in my experience not examinable). When we talk about basic
education we sometimes talk about “reading, writing and arithmetic”.
Aside from the over-emphasis on boring arithmetic (for which we
basically all have phone calculators now), there is again the idea that
for language the skills of reading and writing are separate, but math is
just math.

In this book I'm not going to expect readers to become fluent in all
aspects of category theory. My aim isn't to be able to get you to be
able to do research in category theory, but mainly to be able to read
and appreciate it, and have some build-up into the formality of it in
case you do want to go further. Tourism is sometimes used as a
derogatory word, tourists thought of as superficial visitors who take
selfies and then leave. But well-informed and curious tourists are a
valuable part of cultural exchange. I have always appreciated living in
places that are interesting enough to attract tourists from around the
world. And tourists do sometimes become long-term visitors, permanent
residents, or even citizens. One way to learn a language is to be
deposited in a foreign country where nobody speaks your native tongue,
but I want to do something more gentle than that. The next few chapters
will build up to the formal language gradually.

#+INCLUDE: /home/galaxybeing/Dropbox/org/codeismathiscode2/footer.org :minlevel 1
