2 Prologue

** The status of mathematics
:PROPERTIES:
:CUSTOM_ID: the-status-of-mathematics
:END:
Math has an image problem. Many people are put off it at school and end
up as adults either hating it, being afraid of it, or defensively
boasting about how bad they are at it or how irrelevant it is anyway.
Complaints about math that I hear most commonly from my art students
include that it is rigid, uncreative, and requires too much
memorization; that the questions have nothing to do with real life and
that the answers involve too many rules to be interesting; that it's
useful for scientists and engineers but pointless for anyone else.

On the other hand, as an abstract mathematician I revel in how flexible
and creative the field is, and how /little/ memorization it requires. I
am invigorated and continually re-awakened by how the way of thinking is
pertinent to all aspects of life. I adore how its richness and insight
come from not having to follow anyone else's rules but instead creating
different worlds from different rules and seeing what is possible. And I
believe that while certain parts are useful for science and engineering,
my favorite parts are powerful and illuminating for everyone.

I think there are broadly three reasons math education is important.

- 
  1. As a foundation for further study in mathematical fields.
- 
  2. [@2] For direct usefulness in life.
- 
  3. [@3] To develop a particular way of thinking.

The first point, further study, is the one that is obviously not
relevant to everyone: it doesn't apply if you have absolutely decided
you are not going into further study in mathematical (and by extension
scientific) fields.

The second point, usefulness, is often emphasized as a reason that math
is compulsory for so long at school, but there seems to be a wide range
of views about what this actually means. It certainly doesn't seem to
justify the endless study of triangles, graph sketching, solving
quadratic equations, trigonometric identities and so on. Some people
focus on arithmetic and are convinced that math is important so that we
don't have to rely on calculators to add up our grocery bill, calculate
a tip at a restaurant, or work out how much we'll pay when something is
on sale at 20% off. Others argue that the math we teach is not relevant
enough and we should teach things like mortgages, interest rates, and
how to do your taxes. All of these views are much more utilitarian than
the view this book will take.

The third point is about math as a way of thinking, and is the one that
drives both my research and my teaching. Abstract mathematics is not
just a topic of study. It is a way of thinking that makes connections
between diverse situations to help us unify them and think about them
more efficiently. It focuses our
